### ISSUE TITLE
Error: invalid ExtHeader hash / But Rom works on citra like a charm

### ISSUE THREAD

**Issue by adhoc115** [ihaveamac/3dsconv#12]
Hi,

I tried really every tool out there to transform trimed, decrypted .3ds files to .cia I found on the net. None worked out of the box. With 3dsconv I get at least an error witch is a hint for something.

Here an Examble for "0487 - Legend of Zelda, The - A Link Between Worlds (Europe) (En,Fr,De,Es,It) Decrypted.3ds"

Errorlog:
"C:\Users\*\Desktop\3ds to cia>3dsconv.exe --boot9=boot9.bin --verbose 0487.3ds
3dsconv.py ~ version 4.1
pyaes found, Searching for protected ARM9 bootROM
... boot9.bin: Correct key found.
----------
Processing 0487.3ds...

Title ID: 00040000000EC400

Game Executable CXI Size: 2AABC000
Manual CFA Size: 1D3000
Download Play child CFA Size: 0

Normal key: {normalkey}
Converting 0487 (encrypted)...

Verifying ExtHeader...
Decrypting ExtHeader...
This file may be corrupt (invalid ExtHeader hash).
Done converting 0 out of 1 files. "

The file workes absolutely perfect on citra emu. Why is a transform to .cia always giving that error and how can it be fixed?

Thanks for your work!

**Comment by ihaveamac** [comment]
dunno, it's probably corrupt somewhere and Citra likely does not verify before running. you could try `--ignore-bad-hashes` but this could result in "Invalid NCCH" when attempting to install.

**Comment by adhoc115** [comment]
Thanks for your replay! I got the images from here {link removed}
Even with the command --ignore-bad-hashes its not working. It is also not working for mariocart and zelda orcania of time. Converting a Rom form other source worked today. 
Do you have any idea why none of them from 1ficher is working?

**Comment by ihaveamac** [comment]
no idea, the rom is probably just bad. nothing I can do about it.

**Comment by adhoc115** [comment]
all right, thank for your perfect tool anyway!
Thread can be closed
