### ISSUE TITLE
When I open the .exe archive it instantly closes

### ISSUE THREAD

**Issue by burnmyrique** [ihaveamac/3dsconv#15]
I'm kinda newbie in this encrypting/decrypting/converting thing in the 3DS hacking community (kinda newbie in 3DS hacking in general) and when I try to drag the decrypted .3ds file to the 3dsconv.exe, a prompt pops up on the screen and then automatically closes. What can I do to fix it?

**Comment by ihaveamac** [comment]
run 3dsconv.exe in cmd to check the output

**Comment by burnmyrique** [comment]
I don't know how to do what you said, like mentioned before, I'm pretty newbie with this programming/hacking thing and english is not my native language (I'm brazilian). But, here's a video of what happened: [here](https://www.youtube.com/watch?v=vw4PznaxUqQ)

**Comment by ihaveamac** [comment]
hold shift and right-click in the folder, then use "Open command window here". enter "3dsconv.exe *.3ds" and press enter.

**Comment by burnmyrique** [comment]
This is what happens: [here](https://imgur.com/lF1sA5g)

**Comment by ihaveamac** [comment]
you need to dump boot9 from a 3DS system with boot9strap. hold START+SELECT+X at boot to dump to /boot9strap/boot9.bin, then put in the same folder.

**Comment by burnmyrique** [comment]
Are these dump files the boot9.bin and boot11.bin files?

**Comment by ihaveamac** [comment]
..... yes, that's exactly what I just told you. only boot9 is needed.

**Comment by ihaveamac** [comment]
copy boot9.bin to the same folder with the ".3ds" and try again.

**Comment by burnmyrique** [comment]
Now I got a new error, [here](https://imgur.com/rju6FtZ)

**Comment by burnmyrique** [comment]
The converter say it might be corrupted but I'm still able to run the decrypted .3ds file just fine on Citra

**Comment by ihaveamac** [comment]
incorrect ncch header flags are probably set making it assume encrypted, while citra only ever reads decrypted.

**Comment by burnmyrique** [comment]
And how can I solve this?

**Comment by ihaveamac** [comment]
probably will add a feature to assume decrypted contents, because of tools not setting encrypted flags properly.

**Comment by burnmyrique** [comment]
So there's no way to solve my problem right now? Feels bad :c . Thanks for the help anyway, you were so patient that I'm super impressed knowing how much of a stupid person I am.

**Comment by ihaveamac** [comment]
if you know how to use a hex editor you could change the crypto ncch flags to no-crypto.

**Comment by burnmyrique** [comment]
Unfortunatelly I don't know how use them :c
