### ISSUE TITLE
Decrypted roms detected as Encrypted

### ISSUE THREAD

**Issue by ThisIsAreku** [ihaveamac/3dsconv#18]
I have several *.3ds roms that are already decrypted. They works fine on Citra, but trying to convert them to *.cia leads to an error (`invalid ExtHeader hash`) as 3dsconv try to decrypt them before converting.

I tried to force the `encrypted` variable to `False` (https://github.com/ihaveamac/3dsconv/blob/4f27733527ee4e60eae3914e7b6a44570687867a/3dsconv/3dsconv.py#L330) and the resulting CIA file is working.

**Comment by ihaveamac** [comment]
Because the encryption flags are incorrectly set on the NCCH. They were decrypted with old tools that didn't fix these flags.

**Comment by ThisIsAreku** [comment]
Are you Ok for adding a command line parameter to bypass the encrypted check ? I can submit a PR on this later.

**Comment by ihaveamac** [comment]
If you do this, make sure you fix the flag in the NCCH header, or it won't work on hardware either.

**Comment by ihaveamac** [comment]
Oh, I see that you only needed to change "encrypted" to False and it worked. Sorry, it's been a while since I looked at the code.

**Comment by hyacin75** [comment]
I'm not sure why this option doesn't seem to show up in the current version as this appears to be merged, but I just handpatched from what I saw in the PR and was able to convert some stuff I had in the same boat, so thank you very much @ThisIsAreku for the patch and finding the issue, and of course @ihaveamac for the awesome software!
