### ISSUE TITLE
ncchinfo.bin generation (missing headers)

### ISSUE THREAD

**Issue by pseiler** [ihaveamac/3dsconv#2]
Hi there.
I'm the guy having issues with converting 3ds files with your script. I think the ncchinfo.bin header isn't complete. After your last update the file is valid for converting, but it fails to install. With simple CIA Converter generated xorpads I can build valid CIA files. 
I use Monster Hunter Ultimate 4, which I converted from my cart ridge.

I attached bot ncchinfo.bin files and a screenshot with the error message after installing monster hunter 4 Ultimate.

[ncchinfo.zip](https://github.com/ihaveamac/3dsconv/files/230795/ncchinfo.zip)
[img_20160421_234126](https://cloud.githubusercontent.com/assets/1420501/14725361/d4b2ffa4-081b-11e6-8622-cb60dbcf02ad.jpg)

**Comment by ihaveamac** [comment]
looks like "Simple CIA Converter" uses an older `ncchinfo.bin` format which makes this somewhat more annoying to find out what went wrong.

can you try it with https://github.com/d0k3/Decrypt9WIP/blob/master/scripts/ncchinfo_gen_exh.py ?

**Comment by ihaveamac** [comment]
I only need the `ncchinfo.bin` it outputs, I'm pretty sure it will be valid so you don't need to test it.

**Comment by pseiler** [comment]
It's attached. But i think the missing part in the ncchinfo.bin is the .Main.exefs_norm.xorpad?
Could that be? I used the tool without any arguments

$ python ncchinfo_gen_exh.py roms/Monster_Hunter_Ultimate.3ds

ncchinfo.bin is attached
[ncchinfo_exh.zip](https://github.com/ihaveamac/3dsconv/files/230833/ncchinfo_exh.zip)

**Comment by ihaveamac** [comment]
the ExeFS xorpad is only used by riku's tool to force regionfree, so it's not used at all by my script.

**Comment by ihaveamac** [comment]
"`ncchinfo_exh.bin`" is completely identical to the one generated by my script...

makes me wonder if it's something like make_cia that went wrong.

what region is the game?

**Comment by pseiler** [comment]
Hmm. I can exclude make_cia. With xorpads from simple cia convertered successfully zelda link between worlds. At the moment I use wine to convert my files. This is a good workaround for now^^

**Comment by ihaveamac** [comment]
yeah, well it does kind of bug me that my script is generating a bad CIA. no idea what's going on.

"Invalid NCCH" is usually printed if a hash check fails, in my experience. but if the exheader xorpad was invalid or something, it should have been caught (it verifies the hash of the exheader after decryption). so I'm guessing it's something wrong with building the CIA.

**Comment by ihaveamac** [comment]
hi, can you try converting a smaller rom and seeing if it works whenever you can? thanks.

**Comment by pseiler** [comment]
heyho,

Yeah I will. I will report in the next days

**Comment by ihaveamac** [comment]
is this still an issue?

**Comment by ihaveamac** [comment]
I'll go ahead and close this due to no response for a while. if it's still an issue you can re-open any time
