### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by jon-moreira** [ihaveamac/3dsconv#23]
When i try to run 
``python3 3dsconv.py game.3ds``

i got this error

``
  File "3dsconv.py", line 24
    global boot9_path = os.environ[namevar]
                      ^
SyntaxError: invalid syntax
``
can you help?

Using OSX v. 10.15.2

**Comment by ihaveamac** [comment]
Fixed in bde8c8f1b70531b539e3cdb7595f6b21a0d43085

**Comment by jon-moreira** [comment]
Your fix resolve the first issue, but now...


>  File "3dsconv.py", line 127
>  def print_v(*msg, end='\n'):
>                                      ^
>  SyntaxError: invalid syntax


the icon ^ is down of letter d

**Comment by ihaveamac** [comment]
Make sure you're using Python 3.4 or later, not 2.7.
