### ISSUE TITLE
Can't convert Bravely Default dump properly

### ISSUE THREAD

**Issue by internetakias** [ihaveamac/3dsconv#6]
I made a decrypted, trimmed rip of Bravely Default EU using D9WIP and have tried converting it with 3dsconv multiple times, but the result has always been the same: The converter generates a cxi and a cfa file then exits without making a .cia.
Using the 64 bit Windows version with latest makerom, FYI.

**Comment by internetakias** [comment]
Error log:
- processing: input (decrypted)
  ! makerom had an error.
- full command: makerom -v -f cia -o 00040000000fc600-game-conv.cia -content 000
  40000000fc600-game-conv.cxi:0:0 -content 00040000000fc600-manual.cfa:1:1
- output:
  [CIA] CIA title key: 00000000000000000000000000000000

Traceback (most recent call last):
  File "3dsconv.py", line 376, in <module>
IOError: [Errno 2] No such file or directory: 'work\00040000000fc600-game-conv.
cia'

**Comment by internetakias** [comment]
I redumped. Curiously enough, the new dump had a different md5 checksum but drag and dropping it into 3dsconv still didn't make a cia out of it.

**Comment by ihaveamac** [comment]
does it work with other games?

**Comment by internetakias** [comment]
Works with Fantasy Life EU
I have the feeling Bravely Default's file size (3.26gbs) may be related to the cause, by the way. Do you think it could be that?

**Comment by ihaveamac** [comment]
how much RAM does your computer have?

**Comment by internetakias** [comment]
It's my friend's PC and it's got about 4GBs of ram.

**Comment by ihaveamac** [comment]
makerom is pretty bad and can use lots of memory for larger games. make_cia wasn't any better I think. I don't know if there's anything else you can do atm.

**Comment by internetakias** [comment]
I see. That's a pretty big shame. Oh well.

**Comment by ihaveamac** [comment]
https://github.com/ihaveamac/3dsconv/releases/tag/v3.0

try this.

**Comment by ihaveamac** [comment]
I'll go ahead and close this due to no response for a while. if it's still an issue you can re-open any time

**Comment by internetakias** [comment]
Works fine, thanks
