### ISSUE TITLE
Convert cia to 3ds?

### ISSUE THREAD

**Issue by rpalmon** [ihaveamac/3dsconv#7]
Is there a way that you can convert a cia to a 3ds? Most games I find that I want are cia files but I want to play them as a 3ds rom on my sky3ds+.

**Comment by ihaveamac** [comment]
Sky3DS won't take non-clean dumps. you'll have to dump the game card again or find a ".3ds" version of the game. if the game is only available digitally/CIA format, you just won't be able to run it on Sky3DS regardless, until we can figure out how to get it to run things like homebrew ".3ds" files. even then it will only work on a system with signature patches.

that basically means CIA -> ".3ds" is only useful for use on Gateway and I'd rather not support this. sorry

**Comment by rpalmon** [comment]
Lets say I have a .3ds rom already and an update file. How can I use the update file to update the 3ds rom?

**Comment by ihaveamac** [comment]
I'm not sure what you're trying to do.

**Comment by rpalmon** [comment]
Is there a way to update a 3ds rom that is out of region?

**Comment by ihaveamac** [comment]
install a cia for the update? that's pretty much the only way I know of.

**Comment by mfjordvald** [comment]
@ihaveamac sorry for dragging up an old issue, didn't want to open a new one.

Do you know if it's possible to take an encrypted .3ds file and decrypt it, without a 3DS, so that it works in Citra?

**Comment by ihaveamac** [comment]
you need a 3DS to dump the bootrom, so good luck with that. also 3dsconv doesn't handle decryption.

also don't know about any PC tools that directly decrypt a ".3ds", but you can look at https://github.com/ihaveamac/fuse-3ds to "mount" a file and play a decrypted version in citra (still need the bootrom though)

**Comment by mfjordvald** [comment]
Appreciate you getting back to me so quick. I do have the boot9.bin file, but it does seem like no one made a decrypter that works without the 3DS.
